### ISSUE TITLE
Upload problem rooted in uncleaned rucio metadata

### ISSUE THREAD

**Issue by FaroutYLq** [XENONnT/outsource#126]
Not really a problem for outsource itself. Original slack thread [here](https://xenonnt.slack.com/archives/C048FE2U3KN/p1707090815576129).

Right now, I am trying to upload this file `/ospool/uc-shared/project/xenon/yuanlq/data/051689-peaklets-euocvpkv3y/peaklets-euocvpkv3y-000144`, which you can see doesn’t exist yet as a did.
```
(XENONnT_development) yuanlq@ap23:~/software/admix$ rucio list-files xnt_051689:peaklets-euocvpkv3y
/cvmfs/xenon.opensciencegrid.org/releases/nT/development/anaconda/envs/XENONnT_development/bin/rucio:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('rucio-clients==1.23.14', 'rucio')
+---------------------------------------+--------------------------------------+-------------+------------+----------+
| SCOPE:NAME                            | GUID                                 | ADLER32     | FILESIZE   | EVENTS   |
|---------------------------------------+--------------------------------------+-------------+------------+----------|
| xnt_051689:peaklets-euocvpkv3y-000049 | 1C38CE71-BB8E-46DB-BBE1-1407D5DD160B | ad:0fe6cf5c | 114.435 MB |          |
| xnt_051689:peaklets-euocvpkv3y-000056 | 3AC903B8-5B44-4A2A-92B5-EA4F60346454 | ad:ac35d526 | 119.025 MB |          |
| xnt_051689:peaklets-euocvpkv3y-000245 | 083366AB-C92B-4A67-9CB8-0FD416FAC691 | ad:1dd01840 | 121.214 MB |          |
+---------------------------------------+--------------------------------------+-------------+------------+----------+
Total files : 3
Total size : 354.674 MB
(XENONnT_development) yuanlq@ap23:~/software/admix$ rucio ls xnt_051689:peaklets-euocvpkv3y-000144
/cvmfs/xenon.opensciencegrid.org/releases/nT/development/anaconda/envs/XENONnT_development/bin/rucio:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('rucio-clients==1.23.14', 'rucio')
+--------------+--------------+
| SCOPE:NAME   | [DID TYPE]   |
|--------------+--------------|
+--------------+--------------+
```
However, when I upload by rucio.client.uploadclient.UploadClient().upload , it gives this error:
```
>>> import rucio
>>> client = rucio.client.uploadclient.UploadClient()
>>> to_upload=[{'path': '/ospool/uc-shared/project/xenon/yuanlq/data/051689-peaklets-euocvpkv3y/peaklets-euocvpkv3y-000144', 'rse': 'UC_OSG_USERDISK', 'did_scope': 'xnt_051689', 'did_name': 'peaklets-euocvpkv3y-000144', 'dataset_scope': 'xnt_051689', 'dataset_name': 'peaklets-euocvpkv3y', 'register_after_upload': False, 'lifetime': None}]
>>> client.upload(to_upload)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cvmfs/xenon.opensciencegrid.org/releases/nT/development/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/rucio_clients-1.23.14-py3.9.egg/rucio/client/uploadclient.py", line 203, in upload
    self._register_file(file, registered_dataset_dids)
  File "/cvmfs/xenon.opensciencegrid.org/releases/nT/development/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/rucio_clients-1.23.14-py3.9.egg/rucio/client/uploadclient.py", line 392, in _register_file
    raise DataIdentifierAlreadyExists
rucio.common.exception.DataIdentifierAlreadyExists: Data Identifier Already Exists.
```
After a bit more [source codes reading](https://github.com/rucio/rucio/blob/b36ad2e98b150cc5eb1580c4d35387bcd57ec183/lib/rucio/client/uploadclient.py#L384-L392), it seems that the issue is in metadata… For those who I can successfully upload, before I upload so there is NO metadata, for example:
```
(XENONnT_development) yuanlq@ap23:~/software/admix$ rucio get-metadata xnt_051689:peaklets-euocvpkv3y-000055
/cvmfs/xenon.opensciencegrid.org/releases/nT/development/anaconda/envs/XENONnT_development/bin/rucio:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('rucio-clients==1.23.14', 'rucio')
2024-02-04 18:34:03,014	ERROR	Data identifier not found.
Details: Data identifier 'xnt_051689:peaklets-euocvpkv3y-000055' not found
```
What I don’t understand is why the first upload attempt for a specific file could fail because the metadata for that specific file already existed. Is it possible that somehow the purging  (delete rules + erase) we did before neglected the metadata? It seems indeed that this file’s metadata (for which file I cannot upload because of `rucio.common.exception.DataIdentifierAlreadyExists: Data Identifier Already Exists.`) has escaped all purging since Dec 2023…

```
(XENONnT_development) yuanlq@ap23:~/software/admix$ rucio get-metadata xnt_051689:peaklets-euocvpkv3y-000052
/cvmfs/xenon.opensciencegrid.org/releases/nT/development/anaconda/envs/XENONnT_development/bin/rucio:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('rucio-clients==1.23.14', 'rucio')
access_cnt:      None
accessed_at:     None
account:         production
adler32:         62ff996e
availability:    AVAILABLE
bytes:           131695330
campaign:        None
closed_at:       None
complete:        None
constituent:     None
created_at:      2023-12-02 23:01:52
datatype:        None
deleted_at:      None
did_type:        FILE
eol_at:          None
events:          None
expired_at:      None
guid:            30f3d69612574d78ae52cbbb499d87ff
hidden:          False
is_archive:      None
is_new:          True
is_open:         None
length:          None
lumiblocknr:     None
md5:             b441be3291a5200cf5bacc99a3d02b06
monotonic:       False
name:            peaklets-euocvpkv3y-000052
obsolete:        False
panda_id:        None
phys_group:      None
prod_step:       None
project:         None
provenance:      None
purge_replicas:  True
run_number:      None
scope:           xnt_051689
stream_name:     None
suppressed:      False
task_id:         None
transient:       False
updated_at:      2023-12-02 23:01:52
version:         None
```
This explains why for some runs we have never been able to process.

**Comment by FaroutYLq** [comment]
This is interesting. I just performed `delete-rules` + `erase `on this specific dataset `xnt_051689:peaklets-euocvpkv3y` and you can see that the difference in metadata of the dataset and files associated:
```
>>> import rucio 
>>> didclient = rucio.client.didclient.DIDClient()
>>> didclient.get_metadata('xnt_051689','peaklets-euocvpkv3y')
{'scope': 'xnt_051689',
 'name': 'peaklets-euocvpkv3y',
 'account': 'production',
 'did_type': 'DATASET',
 'is_open': True,
 'monotonic': False,
 'hidden': False,
 'obsolete': False,
 'complete': None,
 'is_new': True,
 'availability': 'AVAILABLE',
 'suppressed': False,
 'bytes': None,
 'length': None,
 'md5': None,
 'adler32': None,
 'expired_at': datetime.datetime(2024, 2, 6, 18, 57, 38),
 'purge_replicas': True,
 'deleted_at': None,
 'events': None,
 'guid': None,
 'project': None,
 'datatype': None,
 'run_number': None,
 'stream_name': None,
 'prod_step': None,
 'version': None,
 'campaign': None,
 'task_id': None,
 'panda_id': None,
 'lumiblocknr': None,
 'provenance': None,
 'phys_group': None,
 'transient': False,
 'accessed_at': None,
 'closed_at': None,
 'eol_at': None,
 'is_archive': None,
 'constituent': None,
 'access_cnt': None,
 'created_at': datetime.datetime(2024, 2, 4, 15, 43, 25),
 'updated_at': datetime.datetime(2024, 2, 5, 18, 57, 38)}
>>> didclient.get_metadata('xnt_051689','peaklets-euocvpkv3y-000052')
{'scope': 'xnt_051689',
 'name': 'peaklets-euocvpkv3y-000052',
 'account': 'production',
 'did_type': 'FILE',
 'is_open': None,
 'monotonic': False,
 'hidden': False,
 'obsolete': False,
 'complete': None,
 'is_new': True,
 'availability': 'AVAILABLE',
 'suppressed': False,
 'bytes': 131695330,
 'length': None,
 'md5': 'b441be3291a5200cf5bacc99a3d02b06',
 'adler32': '62ff996e',
 'expired_at': None,
 'purge_replicas': True,
 'deleted_at': None,
 'events': None,
 'guid': '30f3d69612574d78ae52cbbb499d87ff',
 'project': None,
 'datatype': None,
 'run_number': None,
 'stream_name': None,
 'prod_step': None,
 'version': None,
 'campaign': None,
 'task_id': None,
 'panda_id': None,
 'lumiblocknr': None,
 'provenance': None,
 'phys_group': None,
 'transient': False,
 'accessed_at': None,
 'closed_at': None,
 'eol_at': None,
 'is_archive': None,
 'constituent': None,
 'access_cnt': None,
 'created_at': datetime.datetime(2023, 12, 2, 23, 1, 52),
 'updated_at': datetime.datetime(2023, 12, 2, 23, 1, 52)}
```
Look at the field expired_at , the dataset is gonna vanish in a day (because of erase) but the file’s metadata will NOT. I wonder if there is anything we can do to purge the file, since it has already decoupled from the dataset?
```
>>> didclient.get_did('xnt_051689','peaklets-euocvpkv3y-000052')
{'scope': 'xnt_051689',
 'name': 'peaklets-euocvpkv3y-000052',
 'type': 'FILE',
 'account': 'production',
 'bytes': 131695330,
 'length': 1,
 'md5': 'b441be3291a5200cf5bacc99a3d02b06',
 'adler32': '62ff996e'}
```

**Comment by FaroutYLq** [comment]
Also I don’t understand how did the decoupling happen between files and dataset…

**Comment by FaroutYLq** [comment]
Proposed fix [here](https://github.com/XENONnT/admix/pull/52)
