### ISSUE TITLE
Noop workflow generated for `afterpulses`

### ISSUE THREAD

**Issue by FaroutYLq** [XENONnT/outsource#130]
No idea why it is happening. Currently we are not able to process `afterpulses`, and example workflow can be found here, which is a noop: 
```
(XENONnT_development) [yuanlq@ap23 outsource]$  cd /home/yuanlq/software/outsource ; /usr/bin/env /cvmfs/xenon.opensciencegrid.org/releases/nT/development/anaconda/envs/XENONnT_development/bin/python /home/yuanlq/.vscode-server-insiders/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 50337 -- /home/yuanlq/software/outsource/bin/outsource --run 51777 --name debug_051777_1 --context xenonnt_offline --detector tpc 
2024-02-07 19:04:33,088 - utilix - DEBUG - Token exists at /home/yuanlq/.dbtoken
2024-02-07 19:04:33,088 - utilix - DEBUG - Token exists at /home/yuanlq/.dbtoken
2024-02-07 19:04:33,089 - utilix - DEBUG - Token is valid.
2024-02-07 19:04:33,089 - utilix - DEBUG - Token is valid.
*** Detector definition message ***
You are currently using the default XENON10 template detector.

2024-02-07 19:04:39,303 - utilix - DEBUG - Token exists at /home/yuanlq/.dbtoken
2024-02-07 19:04:39,303 - utilix - DEBUG - Token exists at /home/yuanlq/.dbtoken
DEBUG:utilix:Token exists at /home/yuanlq/.dbtoken
2024-02-07 19:04:39,303 - utilix - DEBUG - Token is valid.
2024-02-07 19:04:39,303 - utilix - DEBUG - Token is valid.
DEBUG:utilix:Token is valid.
2024-02-07 19:04:39,362 - utilix - DEBUG - Token exists at /home/yuanlq/.dbtoken
2024-02-07 19:04:39,362 - utilix - DEBUG - Token exists at /home/yuanlq/.dbtoken
DEBUG:utilix:Token exists at /home/yuanlq/.dbtoken
2024-02-07 19:04:39,362 - utilix - DEBUG - Token is valid.
2024-02-07 19:04:39,362 - utilix - DEBUG - Token is valid.
DEBUG:utilix:Token is valid.
You specified _auto_append_rucio_local=True and you are not on dali compute nodes, so we will add the following rucio local path:  /project/lgrandi/rucio/
/cvmfs/xenon.opensciencegrid.org/releases/nT/development/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/straxen/url_config.py:743: UserWarning: From straxen version 2.1.0 onward, URLConfig parameterswill be sorted alphabetically before being passed to the plugins, this will change the lineage hash for non-sorted URLs. To load data processed with non-sorted URLs, you will need to use an older version.
  warnings.warn(
Skipping neutron_veto data
Skipping muon_veto data
Run modes for runs passing the basic queires: tpc_pmtap
The following are the run numbers passing the basic queries:
[51777]
------------------------------------------
Run modes for runs passing the basic queires and have raw data available: tpc_pmtap
The following are the run numbers passing the basic queries and have raw data available:
[51777]
------------------------------------------
The following are the run numbers passing the basic queries and have no to_process data available:
[51777]
------------------------------------------
You specified _auto_append_rucio_local=True and you are not on dali compute nodes, so we will add the following rucio local path:  /project/lgrandi/rucio/
2024-02-07 19:14:19 WARNING:  Using cutax: /ospool/uc-shared/project/xenon/xenonnt/software/cutax/v1-16-0.tar.gz
defaultdict(<class 'collections.OrderedDict'>, {})
defaultdict(<class 'collections.OrderedDict'>, {})
defaultdict(<class 'collections.OrderedDict'>, {})
edu.isi.pegasus.planner.catalog.transformation.TransformationFactoryException:  Unable to connect to Transformation Catalog with properties{directory=/scratch/yuanlq/workflows/generated/debug_051777_1/transformations}
at edu.isi.pegasus.planner.catalog.transformation.TransformationFactory.loadInstance(TransformationFactory.java:293)
at edu.isi.pegasus.planner.catalog.transformation.TransformationFactory.loadTransformationStoreFromDirectories(TransformationFactory.java:390)
at edu.isi.pegasus.planner.catalog.transformation.TransformationFactory.loadTransformationStoreFromDirectories(TransformationFactory.java:351)
at edu.isi.pegasus.planner.catalog.transformation.TransformationFactory.loadInstanceWithStores(TransformationFactory.java:102)
at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:450)
at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:328)
at edu.isi.pegasus.planner.client.CPlanner.main(CPlanner.java:206)
java.lang.RuntimeException: The File to be used as TC should be defined with the property pegasus.catalog.transformation.file
at edu.isi.pegasus.planner.catalog.transformation.impl.YAML.connect(YAML.java:167)
at edu.isi.pegasus.planner.catalog.transformation.TransformationFactory.loadInstance(TransformationFactory.java:292)
at edu.isi.pegasus.planner.catalog.transformation.TransformationFactory.loadInstanceWithStores(TransformationFactory.java:158)
at edu.isi.pegasus.planner.catalog.transformation.TransformationFactory.loadInstanceWithStores(TransformationFactory.java:104)
at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:450)
at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:328)
at edu.isi.pegasus.planner.client.CPlanner.main(CPlanner.java:206)
2024.02.07 19:19:07.797 CST:
2024.02.07 19:19:07.802 CST:   -----------------------------------------------------------------------
2024.02.07 19:19:07.807 CST:   File for submitting this DAG to HTCondor           : xenonnt-0.dag.condor.sub
2024.02.07 19:19:07.812 CST:   Log of DAGMan debugging messages                   : xenonnt-0.dag.dagman.out
2024.02.07 19:19:07.817 CST:   Log of HTCondor library output                     : xenonnt-0.dag.lib.out
2024.02.07 19:19:07.823 CST:   Log of HTCondor library error messages             : xenonnt-0.dag.lib.err
2024.02.07 19:19:07.828 CST:   Log of the life of condor_dagman itself            : xenonnt-0.dag.dagman.log
2024.02.07 19:19:07.833 CST:
2024.02.07 19:19:07.838 CST:   -no_submit given, not submitting DAG to HTCondor. You can do this with:
2024.02.07 19:19:07.848 CST:   -----------------------------------------------------------------------
2024.02.07 19:19:09.578 CST:   Database version: '5.0.7dev' (sqlite:////home/yuanlq/.pegasus/workflow.db)
2024.02.07 19:19:10.836 CST:   Pegasus database was successfully created.
2024.02.07 19:19:11.317 CST:   Database version: '5.0.7dev' (sqlite:////scratch/yuanlq/workflows/runs/straxen_v2.2.0/xenonnt_offline/debug_051777_1/xenonnt-0.replicas.db)
2024.02.07 19:19:11.369 CST:   Output replica catalog set to jdbc:sqlite:/scratch/yuanlq/workflows/runs/straxen_v2.2.0/xenonnt_offline/debug_051777_1/xenonnt-0.replicas.db
[WARNING]  Submitting to condor xenonnt-0.dag.condor.sub
2024.02.07 19:19:12.436 CST:   Time taken to execute is 5.929 seconds
Worfklow written to 

        /scratch/yuanlq/workflows/runs/straxen_v2.2.0/xenonnt_offline/debug_051777_1
```

**Comment by FaroutYLq** [comment]
Similar issue observed in `/scratch/yuanlq/workflows/runs/straxen_v2.2.1/xenonnt_offline/noop_debug_0`.

To reproduce the issue:
```
outsource --context xenonnt_offline --detector tpc --run 052785 --name noop_debug_0
```

**Comment by dachengx** [comment]
`052785`'s `afterpulses` is already processed. After https://github.com/XENONnT/outsource/pull/202, running:
```
outsource --context xenonnt_offline --xedocs_version global_v16 --image el9.2024.09.1 --run 52785 --debug
```
will not submit any workflow. Hope this is what you want @FaroutYLq .
