### ISSUE TITLE
Debug RunDB API failure on OSG

### ISSUE THREAD

**Issue by FaroutYLq** [XENONnT/outsource#143]
- Since the Chicago mirror is back, all outsource jobs are failing. This is an example: `/scratch/yuanlq/workflows/runs/straxen_v2.2.2/xenonnt_offline/low_concurrency_test_6/00/00/peaklets_ID0000014.out.002` You can see the key error is attached.
- After a bit more digging, I realize that the issue is triggered when RunDB API is initialized [here](https://github.com/XENONnT/utilix/blob/7f27aaeae33af21a33ba0517eceab964d563bf6c/utilix/rundb.py#L114-L119). it complains
```
        urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='xenon-runsdb.grid.uchicago.edu', port=5000): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x149e670f7040>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

**Comment by FaroutYLq** [comment]
Removing nmap, and printing `admix.clients._init_clients()` + `db = DB()` status
```
outsource --context xenonnt_offline --detector tpc --name low_concurrency_test_7 --run 52738 --debug
```
results here
```
/scratch/yuanlq/workflows/runs/straxen_v2.2.2/xenonnt_offline/low_concurrency_test_7
```

**Comment by FaroutYLq** [comment]
`/scratch/yuanlq/workflows/runs/straxen_v2.2.2/xenonnt_offline/low_concurrency_test_7` confirms that `db = DB()` causes the issue.

**Comment by FaroutYLq** [comment]
Checking location of `.dbtoken`... since we are not sure why we have 
```
        Start dir is /srv/pegasus.eydhMohPD. Here's whats inside:
        total 1.7M
        drwx------.  3 osg01 osg01 4.0K May 20 12:12 .
        drwx------. 11 osg01 osg01 4.0K May 20 12:12 ..
        -rwxr-xr-x.  1 osg01 osg01 1.6M May 20 12:12 cutax.tar.gz
        -rwxr-xr-x.  1 osg01 osg01  337 May 20 12:12 .dbtoken
        -rwxr-xr-x.  1 osg01 osg01 3.4K May 20 12:12 peaklets
        drwxr-xr-x.  4 osg01 osg01   78 Feb 20 06:15 pegasus-5.0.7dev-x86_64_rhel_7
        -rwxr-xr-x.  1 osg01 osg01  26K May 20 12:12 runstrax.py
        -rw-r--r--.  1 osg01 osg01  993 May 20 12:11 stage_in_local_staging-davs_0_0.meta
        -rw-r--r--.  1 osg01 osg01  671 May 20 12:11 stage_in_local_staging-davs_0_1.meta
        -rwxr-xr-x.  1 osg01 osg01 2.1K May 20 12:12 .xenon_config
        --- RUCIO/X509 Stuff ---
```
but still see
```
        2024-05-20 12:19:55,286 - utilix - DEBUG - No token exists at /srv/.dbtoken. Creating new one.
```
It has been the case in the past, though we managed to get the new token work.

**Comment by FaroutYLq** [comment]
Now do `export HOME=$PWD`. See if we can use the uploaded `.dbtoken`
```
outsource --context xenonnt_offline --detector tpc --name low_concurrency_test_9 --run 52738 --debug
```
Result here
```
/scratch/yuanlq/workflows/runs/straxen_v2.2.2/xenonnt_offline/low_concurrency_test_9
```

**Comment by FaroutYLq** [comment]
OK now we can initiate the DB at least. It failed 
```
        Processing now...
        We have forced events to save always.
        Initiing clients...
        Clients initiated
        Initiing DB...
        DB initiated
        You specified _auto_append_rucio_local=True and you are not on dali compute nodes, so we will add the following rucio local path: /project/lgrandi/rucio/
        exiting with status 25
```

**Comment by FaroutYLq** [comment]
With a bit more debug info in `/scratch/yuanlq/workflows/runs/straxen_v2.2.2/xenonnt_offline/low_concurrency_test_10`. 
Now this command in trouble is `data = db.get_data(runid, host='rucio-catalogue')`. The problem seems still there: as long as you try to make request through the API, it will timeout.

**Comment by FaroutYLq** [comment]
A more complete traceback
```
        Traceback (most recent call last):
          File "/srv/pegasus.nbcG3K2ZT/./runstrax.py", line 628, in <module>
            main()
          File "/srv/pegasus.nbcG3K2ZT/./runstrax.py", line 363, in main
            to_download = find_data_to_download(runid, out_dtype, st)
          File "/srv/pegasus.nbcG3K2ZT/./runstrax.py", line 109, in find_data_to_download
            data = db.get_data(runid, host='rucio-catalogue')
          File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/utilix/rundb.py", line 279, in get_data
            data = json.loads(self._get(url).text).get('results', {})
          File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/utilix/rundb.py", line 35, in func_wrapper
            st = func(*args, **kwargs)
          File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/utilix/rundb.py", line 199, in _get
            return requests.get(PREFIX + url, headers=self.headers)
          File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/requests/api.py", line 73, in get
            return request("get", url, params=params, **kwargs)
          File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/requests/api.py", line 59, in request
            return session.request(method=method, url=url, **kwargs)
          File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
            resp = self.send(prep, **send_kwargs)
          File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
            r = adapter.send(request, **kwargs)
          File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
            raise ConnectionError(e, request=request)
        requests.exceptions.ConnectionError: HTTPConnectionPool(host='xenon-runsdb.grid.uchicago.edu', port=5000): Max retries exceeded with url: /runs/number/52738/data (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x14bb59ab3640>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

**Comment by FaroutYLq** [comment]
Following [Juidth's suggestions](https://xenonnt.slack.com/archives/C048FE2U3KN/p1716230361756789), we try `rundb_api_url = http://xenon-runsdb.grid.uchicago.edu:80` instead of `rundb_api_url = http://xenon-runsdb.grid.uchicago.edu:5000`.
Results here
```
/scratch/yuanlq/workflows/runs/straxen_v2.2.2/xenonnt_offline/low_concurrency_test_11
```

**Comment by FaroutYLq** [comment]
For unclear reason, it is working now.

**Comment by FaroutYLq** [comment]
Follow up in #147
