### ISSUE TITLE
Complexity in port of rundb_api_url when generating dbtoken

### ISSUE THREAD

**Issue by FaroutYLq** [XENONnT/outsource#147]
Related discussion [here](https://xenonnt.slack.com/archives/C048FE2U3KN/p1716230361756789)
- port 80 is whitelisted from OSG, but port 5000 is not
  - This should have been the case since 2022, but not sure why we kept using 5000 and nothing breaks
- However, you cannot generate new token using 80 from everywhere

Temporary Solution:
- `rm -rf $HOME/.dbtoken$`
- Use 5000, run `utilix.DB()` in terminal to renew `$HOME/.dbtoken$`
- switch to 80, submit outsource jobs
- After 24 hours, all outsource jobs will fail because the token when submitting jobs expires

**Comment by FaroutYLq** [comment]
An example on "you cannot generate new token using 80 from everywhere"
```
>>> utilix.DB()
2024-05-23 09:59:06,824 - utilix - DEBUG - No token exists at /home/yuanlq/.dbtoken. Creating new one.
2024-05-23 09:59:06,824 - utilix - DEBUG - No token exists at /home/yuanlq/.dbtoken. Creating new one.
2024-05-23 09:59:06,824 - utilix - DEBUG - Creating a new token: doing API call now
2024-05-23 09:59:06,824 - utilix - DEBUG - Creating a new token: doing API call now
2024-05-23 09:59:06,916 - utilix - DEBUG - The response contains these keys: ['message']
2024-05-23 09:59:06,916 - utilix - DEBUG - The response contains these keys: ['message']
ERROR:root:API call to create new token failed. Here is the response:
{"message": "The method is not allowed for the requested URL."}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cvmfs/xenon.opensciencegrid.org/releases/nT/development/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/utilix/rundb.py", line 191, in __init__
    token = Token(token_path)
  File "/cvmfs/xenon.opensciencegrid.org/releases/nT/development/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/utilix/rundb.py", line 87, in __init__
    self.new_token()
  File "/cvmfs/xenon.opensciencegrid.org/releases/nT/development/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/utilix/rundb.py", line 134, in new_token
    raise RuntimeError("Creating a new token failed.")
RuntimeError: Creating a new token failed.
```
