### ISSUE TITLE
Pymongo disconnection

### ISSUE THREAD

**Issue by FaroutYLq** [XENONnT/outsource#148]
On top of #147, we also have pymongo problem
```Traceback (most recent call last):
  File "/srv/pegasus.JtBAwM6CK/./runstrax.py", line 628, in <module>
    main()
  File "/srv/pegasus.JtBAwM6CK/./runstrax.py", line 340, in main
    st = getattr(cutax.contexts, args.context)()
  File "/srv/pegasus.JtBAwM6CK/.local/lib/python3.9/site-packages/cutax/contexts.py", line 80, in xenonnt_offline
    st = straxen.contexts.xenonnt(xedocs_version=xedocs_version, _from_cutax=True, **kwargs)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/straxen/contexts.py", line 115, in xenonnt
    st.apply_xedocs_configs(version=xedocs_version, **kwargs)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/straxen/corrections_services.py", line 490, in apply_xedocs_configs
    docs = db.context_configs.find_docs(**filter_kwargs)
  File "<makefun-gen-264>", line 2, in _find_docs
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/rframe/data_accessor.py", line 82, in _find_docs
    return list(self._find_iter(skip=skip, limit=limit, sort=sort, **labels))
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/rframe/data_accessor.py", line 85, in _find_iter
    for doc in self._find(skip=skip, limit=limit, sort=sort, **labels):
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/rframe/data_accessor.py", line 67, in _find
    for doc in query.iter(limit=limit, skip=skip, sort=sort):
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/rframe/interfaces/mongo.py", line 202, in iter
    docs = list(self.collection.aggregate(pipeline, allowDiskUse=allow_disk_use))
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/pymongo/collection.py", line 2691, in aggregate
    return self._aggregate(
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/pymongo/collection.py", line 2605, in _aggregate
    return self.__database.client._retryable_read(
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1609, in _retryable_read
    with self._secondaryok_for_server(read_pref, server, session) as (
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1461, in _secondaryok_for_server
    with self._get_socket(server, session) as sock_info:
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1396, in _get_socket
    with server.get_socket(self.__all_credentials, handler=err_handler) as sock_info:
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/pymongo/pool.py", line 1371, in get_socket
    sock_info = self._get_socket(all_credentials)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/pymongo/pool.py", line 1436, in _get_socket
    sock_info = self.connect(all_credentials)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/pymongo/pool.py", line 1334, in connect
    sock_info.hello(all_credentials)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/pymongo/pool.py", line 595, in hello
    return self._hello(None, None, None, all_credentials)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/pymongo/pool.py", line 628, in _hello
    doc = self.command("admin", cmd, publish_events=False, exhaust_allowed=awaitable)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/pymongo/pool.py", line 769, in command
    self._raise_connection_failure(error)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/pymongo/pool.py", line 740, in command
    return command(
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/pymongo/network.py", line 167, in command
    reply = receive_message(sock_info, request_id)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/pymongo/network.py", line 225, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/pymongo/network.py", line 327, in _receive_data_on_socket
    raise AutoReconnect("connection closed")
pymongo.errors.AutoReconnect: connection closed
```
It is becoming number 1 problem right now! This is the pymongo related things in xenon_config
```
pymongo_url = xenon-rundb.grid.uchicago.edu:27017,xenon1t-daq.lngs.infn.it:27017,fried.rice.edu:27017/xenonnt
```

**Comment by FaroutYLq** [comment]
Switched from `pymongo_url = xenon1t-daq.lngs.infn.it:27017,fried.rice.edu:27017/xenonnt` to `pymongo_url = xenon-rundb.grid.uchicago.edu:27017,xenon1t-daq.lngs.infn.it:27017,fried.rice.edu:27017/xenon` doesn't really help to order of magnitude

**Comment by FaroutYLq** [comment]
This might be related
```
Traceback (most recent call last):
  File "/srv/pegasus.Vkqthv2kM/./runstrax.py", line 628, in <module>
    main()
  File "/srv/pegasus.Vkqthv2kM/./runstrax.py", line 340, in main
    st = getattr(cutax.contexts, args.context)()
  File "/srv/pegasus.Vkqthv2kM/.local/lib/python3.9/site-packages/cutax/contexts.py", line 80, in xenonnt_offline
    st = straxen.contexts.xenonnt(xedocs_version=xedocs_version, _from_cutax=True, **kwargs)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/straxen/contexts.py", line 112, in xenonnt
    st.apply_cmt_version(cmt_version)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/straxen/corrections_services.py", line 415, in apply_cmt_version
    local_versions = get_cmt_local_versions(cmt_global_version)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/straxen/corrections_services.py", line 400, in get_cmt_local_versions
    return cmt.get_local_versions(global_version)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/straxen/corrections_services.py", line 354, in get_local_versions
    cmt_global = self.interface.read("global_xenonnt")
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/corrections.py", line 112, in read
    df = pdm.read_mongo(correction, [], self.client[self.database_name])
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/pdmongo/core.py", line 159, in read_mongo
    db[collection].aggregate(query, **{**params, **extra}),
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/pymongo/collection.py", line 2690, in aggregate
    with self.__database.client._tmp_session(session, close=False) as s:
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/pymongo/mongo_client.py", line 2040, in _tmp_session
    s = self._ensure_session(session)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/pymongo/mongo_client.py", line 2027, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1976, in __start_session
    server_session = self._get_server_session()
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/pymongo/mongo_client.py", line 2013, in _get_server_session
    return self._topology.get_server_session()
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/pymongo/topology.py", line 525, in get_server_session
    session_timeout = self._check_session_support()
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/pymongo/topology.py", line 507, in _check_session_support
    self._select_servers_loop(
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/pymongo/topology.py", line 226, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: xenon-rundb.grid.uchicago.edu:27017: [Errno 104] Connection reset by peer, Timeout: 30s, Topology Description: <TopologyDescription id: 664e819537e8cd656bcb7aa9, topology_type: Single, servers: [<ServerDescription ('xenon-rundb.grid.uchicago.edu', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('xenon-rundb.grid.uchicago.edu:27017: [Errno 104] Connection reset by peer')>]>
```
Details in `/scratch/yuanlq/workflows/runs/straxen_v2.2.2/xenonnt_offline/dacheng236_20240522_1`

**Comment by FaroutYLq** [comment]
<img width="1038" alt="image" src="https://github.com/XENONnT/outsource/assets/47046530/48c4cc36-5137-4759-81e2-d8daf4903084">
DB pressure doesn't really seems high...?

**Comment by FaroutYLq** [comment]
Test following Ivy's suggestion: use `pymongo_url = xenon-rundb.grid.uchicago.edu:27017` only. Starting from this pressure:
<img width="1046" alt="image" src="https://github.com/XENONnT/outsource/assets/47046530/786df39a-44c1-4e66-93ab-43cb54019546">

**Comment by FaroutYLq** [comment]
Saturated now
<img width="1068" alt="image" src="https://github.com/XENONnT/outsource/assets/47046530/1ab7611d-168a-4a4a-b00c-662b91f8476d">
```
yuanlq xenonnt-0.dag+13151241         5/23 10:38    676    466   3671     38   6249 13151254.0 ... 13157773.0
```
