### ISSUE TITLE
Gfal+rucio when binding /cvmfs 

### ISSUE THREAD

**Issue by ershockley** [XENONnT/outsource#5]
Sometimes jobs fail because of problems downloading from rucio, giving an error of `Protocol implementation not found`. 

The rucio API doesn’t always give the most useful errors so I tried replicating on the login node. It seems like there is some conflict between environments if /cvmfs is binded to the container, causing gfal errors, see the gist I link below. I’m not 100% sure this is exactly what’s happening on the grid but the error does look similar. So maybe some of the jobs land on sites that don’t see /cvmfs or the env is setup in such a way that it doesn’t run into this error? I don't know why else the jobs would succeed sometimes and fail others when downloading files from the same run. 

If I don’t bind /cvmfs when starting the container, I can do rucio downloads without a problem, but I can’t use outsource because it can’t find Pegasus. I can see Pegasus binaries are installed in the container -- I guess that’s separate from the python bindings though? At least in my local repo I use the pegasus at `pegasus_path = /cvmfs/oasis.opensciencegrid.org/osg/projects/pegasus/rhel7/4.9.2dev` and I can't import pegasus [if I don't append this to my path](https://github.com/XENONnT/outsource/blob/master/outsource/Outsource.py#L19). 

The errors I got and debugging process are outlined in this gist:  https://gist.github.com/ershockley/a72a72a3dad8403d174dc5248cc2f777

@rynge any ideas?

**Comment by ershockley** [comment]
Here is an example error of the rucio I see on the grid:

```
Processing now...

Attempting download of x1t_SR001_170621_0617_tpc:raw_records-7k65yaooed-000193 and x1t_SR001_170621_0617_tpc:raw_records-7k65yaooed-metadata.json from UC_OSG_USERDISK ...
Protocol implementation not found
Traceback (most recent call last):
  File "./runstrax.py", line 149, in <module>
    main()
  File "./runstrax.py", line 113, in main
    for ik in ds:
TypeError: 'int' object is not iterable
exiting with status 25
```

**Comment by ershockley** [comment]
This was a problem of a .pth file in my .local directory. I hate those things sometimes...
