### ISSUE TITLE
Trying to fetch a chunk which doesn't exist

### ISSUE THREAD

**Issue by FaroutYLq** [XENONnT/outsource#51]
More details can be found in `/scratch/yuanlq/workflows/runs/straxen_v2.1.0/xenonnt_offline/sr0_ar37_786-787_0`.

```
----------------Task #1 - events - ID0000032 - Kickstart stderr-----------------

 WARNING: X509_CERT_DIR is set set and could lead to problems when using this environment
/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/straxen/url_config.py:707: FutureWarning: From straxen version 2.1.0 onward, URLConfig parameters will be sorted alphabetically before being passed to the plugins, this will change the lineage hash for non-sorted URLs. To load data processed with non-sorted URLs, you will need to use an older version.
  warnings.warn("From straxen version 2.1.0 onward, URLConfig parameters will be sorted alphabetically before being passed to the plugins, this will change the lineage hash for non-sorted URLs. To load data processed with non-sorted URLs, you will need to use an older version.", FutureWarning)
/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/chunk.py:364: NumbaExperimentalFeatureWarning: Record(Start time since unix epoch [ns][type=int64;offset=0;title=Start time since unix epoch [ns]],time[type=int64;offset=0;title=Start time since unix epoch [ns]],Length of the interval in samples[type=int32;offset=8;title=Length of the interval in samples],length[type=int32;offset=8;title=Length of the interval in samples],Width of one sample [ns][type=int32;offset=12;title=Width of one sample [ns]],dt[type=int32;offset=12;title=Width of one sample [ns]],Channel/PMT number[type=int16;offset=16;title=Channel/PMT number],channel[type=int16;offset=16;title=Channel/PMT number],Classification of the peak(let)[type=int8;offset=18;title=Classification of the peak(let)],type[type=int8;offset=18;title=Classification of the peak(let)],Integral across channels [PE][type=float32;offset=19;title=Integral across channels [PE]],area[type=float32;offset=19;title=Integral across channels [PE]],Integral per channel [PE][type=nestedarray(float32, (494,));offset=23;title=Integral per channel [PE]],area_per_channel[type=nestedarray(float32, (494,));offset=23;title=Integral per channel [PE]],Number of hits contributing at least one sample to the peak [type=int32;offset=1999;title=Number of hits contributing at least one sample to the peak ],n_hits[type=int32;offset=1999;title=Number of hits contributing at least one sample to the peak ],Waveform data in PE/sample (not PE/ns!)[type=nestedarray(float32, (200,));offset=2003;title=Waveform data in PE/sample (not PE/ns!)],data[type=nestedarray(float32, (200,));offset=2003;title=Waveform data in PE/sample (not PE/ns!)],Waveform data in PE/sample (not PE/ns!), top array[type=nestedarray(float32, (200,));offset=2803;title=Waveform data in PE/sample (not PE/ns!), top array],data_top[type=nestedarray(float32, (200,));offset=2803;title=Waveform data in PE/sample (not PE/ns!), top array],Peak widths in range of central area fraction [ns][type=nestedarray(float32, (11,));offset=3603;title=Peak widths in range of central area fraction [ns]],width[type=nestedarray(float32, (11,));offset=3603;title=Peak widths in range of central area fraction [ns]],Peak widths: time between nth and 5th area decile [ns][type=nestedarray(float32, (11,));offset=3647;title=Peak widths: time between nth and 5th area decile [ns]],area_decile_from_midpoint[type=nestedarray(float32, (11,));offset=3647;title=Peak widths: time between nth and 5th area decile [ns]],Does the channel reach ADC saturation?[type=nestedarray(int8, (494,));offset=3691;title=Does the channel reach ADC saturation?],saturated_channel[type=nestedarray(int8, (494,));offset=3691;title=Does the channel reach ADC saturation?],Total number of saturated channels[type=int16;offset=4185;title=Total number of saturated channels],n_saturated_channels[type=int16;offset=4185;title=Total number of saturated channels],Channel within tight range of mean[type=int16;offset=4187;title=Channel within tight range of mean],tight_coincidence[type=int16;offset=4187;title=Channel within tight range of mean],Largest gap between hits inside peak [ns][type=int32;offset=4189;title=Largest gap between hits inside peak [ns]],max_gap[type=int32;offset=4189;title=Largest gap between hits inside peak [ns]],Maximum interior goodness of split[type=float32;offset=4193;title=Maximum interior goodness of split],max_goodness_of_split[type=float32;offset=4193;title=Maximum interior goodness of split],Largest time difference between apexes of hits inside peak [ns][type=int32;offset=4197;title=Largest time difference between apexes of hits inside peak [ns]],max_diff[type=int32;offset=4197;title=Largest time difference between apexes of hits inside peak [ns]],Smallest time difference between apexes of hits inside peak [ns][type=int32;offset=4201;title=Smallest time difference between apexes of hits inside peak [ns]],min_diff[type=int32;offset=4201;title=Smallest time difference between apexes of hits inside peak [ns]];4205;False) has been considered a subtype of Record(Start time since unix epoch [ns][type=int64;offset=0;title=Start time since unix epoch [ns]],time[type=int64;offset=0;title=Start time since unix epoch [ns]],Length of the interval in samples[type=int32;offset=8;title=Length of the interval in samples],length[type=int32;offset=8;title=Length of the interval in samples],Width of one sample [ns][type=int32;offset=12;title=Width of one sample [ns]],dt[type=int32;offset=12;title=Width of one sample [ns]],Channel/PMT number[type=int16;offset=16;title=Channel/PMT number],channel[type=int16;offset=16;title=Channel/PMT number],Classification of the peak(let)[type=int8;offset=18;title=Classification of the peak(let)],type[type=int8;offset=18;title=Classification of the peak(let)];19;False)  This is an experimental feature.
  strax.endtime(d))
/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/straxen/storage/mongo_storage.py:340: DownloadWarning: Downloading xnt_gcn_SR0_mix_2000030_2000020_20211211.tar.gz to /tmp/straxen_resource_cache/b8baee8874d4f688303d9d524a2a9746
  warn(f'Downloading {config_name} to {destination_path}',
2023-06-30 06:26:03.335769: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-30 06:26:04.249902: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-30 06:26:04.251597: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-30 06:26:08.612425: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Exception in thread build:peaks:
Traceback (most recent call last):
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/mailbox.py", line 294, in _send_from
    self.kill_from_exception(e)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/mailbox.py", line 213, in kill_from_exception
    raise e
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/mailbox.py", line 281, in _send_from
    x = next(iterable)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/plugins/plugin.py", line 452, in iter
    self._fetch_chunk(
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/plugins/plugin.py", line 373, in _fetch_chunk
    [self.input_buffer[d], next(iters[d])])
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/mailbox.py", line 438, in _read
    res = msg.result()
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/storage/files.py", line 249, in _read_and_format_chunk
    chunk = super()._read_and_format_chunk(*args, **kwargs)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/storage/common.py", line 508, in _read_and_format_chunk
    data = self._read_chunk(backend_key,
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/straxen/storage/rucio_remote.py", line 164, in _read_chunk
    downloaded = admix.download(chunk_did, rse=rse, location=self.staging_dir)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/admix/downloader.py", line 85, in download
    did_type = get_did_type(did)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/admix/clients.py", line 39, in wrapped
    return func(*args, **kwargs)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/admix/rucio.py", line 99, in get_did_type
    return clients.rucio_client.get_did(scope, name)['type']
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/rucio_clients-1.23.14-py3.9.egg/rucio/client/didclient.py", line 427, in get_did
rucio.common.exception.DataIdentifierNotFound: Data identifier not found.
Details: Data identifier 'xnt_032153:merged_s2s-qkatogwl36-000005' not found
Target Mailbox (peak_positions_gcn) killed, exception <class 'strax.mailbox.MailboxKilled'>, message (<class 'rucio.common.exception.DataIdentifierNotFound'>, DataIdentifierNotFound("Data identifier 'xnt_032153:merged_s2s-qkatogwl36-000005' not found"), <traceback object at 0x1554a4cb5d80>)
Traceback (most recent call last):
  File "/srv/pegasus.UjarGpDUa/./runstrax.py", line 486, in <module>
    main()
  File "/srv/pegasus.UjarGpDUa/./runstrax.py", line 323, in main
    process(runid,
  File "/srv/pegasus.UjarGpDUa/./runstrax.py", line 139, in process
    st.make(runid_str, keystring,
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/context.py", line 1414, in make
    for _ in self.get_iter(run_ids[0], targets,
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/context.py", line 1324, in get_iter
    generator.throw(e)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/context.py", line 1296, in get_iter
    for n_chunks, result in enumerate(strax.continuity_check(generator), 1):
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/chunk.py", line 303, in continuity_check
    for chunk in chunk_iter:
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/processor.py", line 302, in iter
    raise exc.with_traceback(traceback)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/mailbox.py", line 281, in _send_from
    x = next(iterable)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/plugins/plugin.py", line 452, in iter
    self._fetch_chunk(
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/plugins/plugin.py", line 373, in _fetch_chunk
    [self.input_buffer[d], next(iters[d])])
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/mailbox.py", line 438, in _read
    res = msg.result()
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/storage/files.py", line 249, in _read_and_format_chunk
    chunk = super()._read_and_format_chunk(*args, **kwargs)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/storage/common.py", line 508, in _read_and_format_chunk
    data = self._read_chunk(backend_key,
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/straxen/storage/rucio_remote.py", line 164, in _read_chunk
    downloaded = admix.download(chunk_did, rse=rse, location=self.staging_dir)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/admix/downloader.py", line 85, in download
    did_type = get_did_type(did)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/admix/clients.py", line 39, in wrapped
    return func(*args, **kwargs)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/admix/rucio.py", line 99, in get_did_type
    return clients.rucio_client.get_did(scope, name)['type']
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/rucio_clients-1.23.14-py3.9.egg/rucio/client/didclient.py", line 427, in get_did
rucio.common.exception.DataIdentifierNotFound: Data identifier not found.
Details: Data identifier 'xnt_032153:merged_s2s-qkatogwl36-000005' not found
```

**Comment by FaroutYLq** [comment]
There should be no chunk 000005. Why are we trying to fetch it?
```
(XENONnT_development) yuanlq@dali-login2:~$ rucio list-files xnt_032153:merged_s2s-qkatogwl36
+------------------------------------------------+--------------------------------------+-------------+------------+----------+
| SCOPE:NAME                                     | GUID                                 | ADLER32     | FILESIZE   | EVENTS   |
|------------------------------------------------+--------------------------------------+-------------+------------+----------|
| xnt_032153:merged_s2s-qkatogwl36-000000        | 38AF5FBA-5ED6-40CC-8F0A-15A06E1F48DB | ad:7425f445 | 95.337 MB  |          |
| xnt_032153:merged_s2s-qkatogwl36-000001        | AED59752-B1C3-417F-BB98-327CFDB40DE4 | ad:5b879f34 | 95.097 MB  |          |
| xnt_032153:merged_s2s-qkatogwl36-000002        | 59B25455-6642-4388-B8E6-8ADD8D954386 | ad:517e756a | 95.596 MB  |          |
| xnt_032153:merged_s2s-qkatogwl36-000003        | CFC54323-162A-47C4-A096-51E5B36019AD | ad:e502ada0 | 93.844 MB  |          |
| xnt_032153:merged_s2s-qkatogwl36-000004        | FC1EA202-3240-44BB-8366-8F92EB823FEC | ad:e2ae465c | 89.592 MB  |          |
| xnt_032153:merged_s2s-qkatogwl36-metadata.json | 4793E002-3772-43F6-BF1B-D2BA45C61402 | ad:ad9657e0 | 8.954 kB   |          |
+------------------------------------------------+--------------------------------------+-------------+------------+----------+
Total files : 6
Total size : 469.474 MB
```

**Comment by dachengx** [comment]
What is in metadata?

**Comment by FaroutYLq** [comment]
Original file here on midway3. `/project/lgrandi/rucio/xnt_032153/92/ef/merged_s2s-qkatogwl36-metadata.json` It does seem to include a chunk 000005. It is possible that the data transfer failed but somehow the checksum is passed. If that is the case it is the problem of computing pipeline.
```
        {
            "chunk_i": 4,
            "end": 1636718719249116659,
            "filename": "merged_s2s-qkatogwl36-000004",
            "first_endtime": 1636718397127348440,
            "first_time": 1636718397127311960,
            "last_endtime": 1636718719246583690,
            "last_time": 1636718719246551050,
            "n": 50358,
            "nbytes": 211755390,
            "run_id": "032153",
            "start": 1636718397126569459,
            "subruns": null
        },
```

**Comment by FaroutYLq** [comment]
Seems indeed this is the case... Sorry to bug @jmosbacher, in your experience did you ever see this?
```
(XENONnT_development) yuanlq@dali-login2:~$ rucio list-rules xnt_032153:merged_s2s-qkatogwl36
ID                                ACCOUNT     SCOPE:NAME                        STATE[OK/REPL/STUCK]    RSE_EXPRESSION        COPIES  EXPIRES (UTC)    CREATED (UTC)
--------------------------------  ----------  --------------------------------  ----------------------  ------------------  --------  ---------------  -------------------
59521a8aef744393a687f45b7c3599ed  production  xnt_032153:merged_s2s-qkatogwl36  OK[6/0/0]               UC_MIDWAY_USERDISK         1                   2023-06-30 04:26:03
```

**Comment by jmosbacher** [comment]
@FaroutYLq yeah i have seen this many times in the last reprocessing campaign. I didn't really have time to try to debug it so i just resubmitted these runs and many times resubmitting them works but i think many just kept failing.

**Comment by FaroutYLq** [comment]
A list of DIDs with data corrupted (incomplete). Considering how adjacent they are in run number, it could be related to failure of data transfer node in midway.
