### ISSUE TITLE
Massive failure in combine jobs when staging/uploading

### ISSUE THREAD

**Issue by FaroutYLq** [XENONnT/outsource#57]
An example: `/scratch/yuanlq/workflows/runs/straxen_v2.1.1/xenonnt_offline/43043_1`.

This happens even when the workload is pretty low.
```
----------------Task #1 - combine - ID0000001 - Kickstart stderr----------------

 WARNING: X509_CERT_DIR is set set and could lead to problems when using this environment
/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/straxen/url_config.py:711: UserWarning: From straxen version 2.1.0 onward, URLConfig parameterswill be sorted alphabetically before being passed to the plugins, this will change the lineage hash for non-sorted URLs. To load data processed with non-sorted URLs, you will need to use an older version.
  warnings.warn("From straxen version 2.1.0 onward, URLConfig parameters"
No <rechunk_to_mb> specified!
No <rechunk_to_mb> specified!
No <rechunk_to_mb> specified!
No <rechunk_to_mb> specified!
Traceback (most recent call last):
  File "/srv/pegasus.PGR8F6hoQ/./combine.py", line 161, in <module>
    main()
  File "/srv/pegasus.PGR8F6hoQ/./combine.py", line 157, in main
    admix.upload(this_path, rse=rse, did=dataset_did, update_db=args.update_db)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/admix/uploader.py", line 80, in upload
    clients.upload_client.upload(to_upload)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/rucio_clients-1.23.14-py3.9.egg/rucio/client/uploadclient.py", line 330, in upload
rucio.common.exception.NoFilesUploaded: None of the given files have been uploaded.
```

**Comment by FaroutYLq** [comment]
<img width="2517" alt="image" src="https://github.com/XENONnT/outsource/assets/47046530/ba4de752-701e-4613-b21f-6f8b8e3f141c">
`/scratch/yuanlq/workflows/runs/straxen_v2.1.1/xenonnt_offline/43043_1/00/00/combine_ID0000001.err.004`
```
############################ Staging out output files ############################
2023-07-24 17:44:41,894    INFO:  Reading URL pairs from stdin
2023-07-24 17:44:41,894    INFO:  1 transfers loaded
2023-07-24 17:44:41,894    INFO:  PATH=/srv/pegasus.PGR8F6hoQ/pegasus-5.0.6dev-x86_64_rhel_7/bin:/opt/XENONnT/anaconda/envs/XENONnT_development/bin:/opt/XENONnT/anaconda/condabin:/opt/rh/devtoolset-9/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
2023-07-24 17:44:41,894    INFO:  LD_LIBRARY_PATH=/opt/XENONnT/anaconda/envs/XENONnT_development/lib64:/opt/XENONnT/anaconda/envs/XENONnT_development/lib:/opt/rh/devtoolset-9/root/usr/lib64:/opt/rh/devtoolset-9/root/usr/lib:/opt/rh/devtoolset-9/root/usr/lib64/dyninst:/opt/rh/devtoolset-9/root/usr/lib/dyninst:/opt/rh/devtoolset-9/root/usr/lib64:/opt/rh/devtoolset-9/root/usr/lib:/lib
2023-07-24 17:44:41,972    INFO:  --------------------------------------------------------------------------------
2023-07-24 17:44:41,972    INFO:  Starting transfers - attempt 1
/bin/sh: line 1: 1560150 Segmentation fault      gfal-copy --version 2>&1
2023-07-24 17:44:44,693    INFO:  Tool found: gfal-copy   Version:    Path: /opt/XENONnT/anaconda/envs/XENONnT_development/bin/gfal-copy
2023-07-24 17:44:44,693   ERROR:  Expected local file does not exist: /srv/pegasus.PGR8F6hoQ/043043-peaklets-combined.tar.gz
2023-07-24 17:46:50,793    INFO:  --------------------------------------------------------------------------------
2023-07-24 17:46:50,793    INFO:  Starting transfers - attempt 2
2023-07-24 17:46:52,795   ERROR:  Expected local file does not exist: /srv/pegasus.PGR8F6hoQ/043043-peaklets-combined.tar.gz
2023-07-24 17:51:52,864    INFO:  --------------------------------------------------------------------------------
2023-07-24 17:51:52,864    INFO:  Starting transfers - attempt 3
2023-07-24 17:51:54,867   ERROR:  Expected local file does not exist: /srv/pegasus.PGR8F6hoQ/043043-peaklets-combined.tar.gz
2023-07-24 17:51:54,867    INFO:  --------------------------------------------------------------------------------
2023-07-24 17:51:54,868    INFO:  Stats: Total 3 transfers, 0.0 B transferred in 433 seconds. Rate: 0.0 B/s (0.0 b/s)
2023-07-24 17:51:54,868    INFO:         Between sites condorpool->staging : 3 transfers, 0.0 B transferred in 433 seconds. Rate: 0.0 B/s (0.0 b/s)
2023-07-24 17:51:54,868 CRITICAL:  Some transfers failed! See above, and possibly stderr.
2023-07-24 17:51:54: Last command exited with 1
2023-07-24 17:51:59: /srv/pegasus.PGR8F6hoQ cleaned up
PegasusLite: exitcode 1
```

**Comment by FaroutYLq** [comment]
`/scratch/yuanlq/workflows/runs/straxen_v2.1.1/xenonnt_offline/43043_1/00/00/combine_ID0000001.out.004`

```
---------------pegasus-multipart
- transfer_attempts:
  - src_url: "file:///srv/pegasus.PGR8F6hoQ/043043-peaklets-combined.tar.gz"
    src_label: "condorpool"
    dst_url: "gsiftp://xenon-gridftp.grid.uchicago.edu:2811/xenon/workflow_scratch/yuanlq/43043_1/00/00/043043-peaklets-combined.tar.gz"
    dst_label: "staging"
    success: False
    start: 1690220685
    duration: 0.0
    lfn: "043043-peaklets-combined.tar.gz"
  - src_url: "file:///srv/pegasus.PGR8F6hoQ/043043-peaklets-combined.tar.gz"
    src_label: "condorpool"
    dst_url: "gsiftp://xenon-gridftp.grid.uchicago.edu:2811/xenon/workflow_scratch/yuanlq/43043_1/00/00/043043-peaklets-combined.tar.gz"
    dst_label: "staging"
    success: False
    start: 1690220813
    duration: 0.0
    lfn: "043043-peaklets-combined.tar.gz"
  - src_url: "file:///srv/pegasus.PGR8F6hoQ/043043-peaklets-combined.tar.gz"
    src_label: "condorpool"
    dst_url: "gsiftp://xenon-gridftp.grid.uchicago.edu:2811/xenon/workflow_scratch/yuanlq/43043_1/00/00/043043-peaklets-combined.tar.gz"
    dst_label: "staging"
    success: False
    start: 1690221115
    duration: 0.0
    lfn: "043043-peaklets-combined.tar.gz"
```

**Comment by FaroutYLq** [comment]
The issue seems that the `peaklets` are not combined as wished by the time we want to upload

```
yuanlq@login:/xenon_dcache/workflow_scratch/yuanlq/43043_1/00/00$ ls
043043-output-peaklets-0000.tar.gz  043043-output-peaklets-0004.tar.gz	combine.py
043043-output-peaklets-0001.tar.gz  043043-output-peaklets-0005.tar.gz	cutax.tar.gz
043043-output-peaklets-0002.tar.gz  043043-output-peaklets-0006.tar.gz	events
043043-output-peaklets-0003.tar.gz  combine				runstrax.py
```

**Comment by FaroutYLq** [comment]
Seems related to data corruption
```
| xnt_043043:peaklets-ui5hguaz2k-000102        | E5C43AF7-77CA-4581-8850-394E434A184C | ad:61f2b3fc | 66.638 MB  |          |
| xnt_043043:peaklets-ui5hguaz2k-000103        | 877BA742-D9A2-47EE-AB31-6E8DDC21FF0B | ad:f06f1733 | 53.263 MB  |          |
| xnt_043043:peaklets-ui5hguaz2k-000105        | CC4BD588-1918-4710-8C0A-60620A667700 | ad:339a8436 | 65.881 MB  |          |
| xnt_043043:peaklets-ui5hguaz2k-000106        | 9D958A23-8112-47A9-81D6-8BA7E7D3C188 | ad:b6cc7fe9 | 61.610 MB  |
```

**Comment by FaroutYLq** [comment]
Same mechanism will happen to any multi-chunk data types. Can we tar before transferring?

**Comment by FaroutYLq** [comment]
No, it is not ideal. Because it will lead to lots of headache on midway to untar.

**Comment by FaroutYLq** [comment]
Maybe at least we should check file numbers and compare with meta data's prediction before uploading. So do some surgery at `straw-wrapper.sh`.

**Comment by FaroutYLq** [comment]
Just for the record, we started another fresh one (never processed) at `/scratch/yuanlq/workflows/runs/straxen_v2.1.1/xenonnt_offline/44237_0` for comparison
![image](https://github.com/XENONnT/outsource/assets/47046530/a6d0d4ce-6a3e-4ef0-8fd0-8f5be7177cc9)

**Comment by FaroutYLq** [comment]
> Maybe at least we should check file numbers and compare with meta data's prediction before uploading. So do some surgery at `straw-wrapper.sh`.

No it won't help. 

`/scratch/yuanlq/workflows/runs/straxen_v2.1.1/xenonnt_offline/43043_1/00/00/peaklets_ID0000002.out.00` says

```
        -rw-r--r--. 1 osg osg  404 Jul 24 16:25 metadata_lone_hits-ui5hguaz2k-000015.json
        -rw-r--r--. 1 osg osg  404 Jul 24 16:25 metadata_lone_hits-ui5hguaz2k-000016.json
        -rw-r--r--. 1 osg osg  404 Jul 24 16:25 metadata_lone_hits-ui5hguaz2k-000017.json
```

However, `rucio list-files xnt_043043:peaklets-ui5hguaz2k` says


```
| xnt_043043:peaklets-ui5hguaz2k-000015        | 2203D710-9092-4ADE-BC92-7F22CB8E1CFA | ad:0666c014 | 54.446 MB  |          |
| xnt_043043:peaklets-ui5hguaz2k-000017        | 44361346-E1B5-42FE-8A22-B0E3517083E9 | ad:fa851d51 | 61.560 MB  |          |
```

**Comment by FaroutYLq** [comment]
```
| xnt_043101:peaklets-ui5hguaz2k-000143        | 8E29966B-BA64-4018-90AD-E5D38B957675 | ad:fdf55c1a | 66.386 MB  |          |
| xnt_043101:peaklets-ui5hguaz2k-000145        | 271400B8-B1BC-4AC0-AA14-491B1048A4E4 | ad:6129f5db | 61.456 MB  |          |
```

A even more weird case:
```
Singularity xenonnt-development.simg:/project/lgrandi/rucio/xnt_043101> find . -type f -name "*peaklets-ui5hguaz2k-000144"
./5a/44/peaklets-ui5hguaz2k-000144
Singularity xenonnt-development.simg:/project/lgrandi/rucio/xnt_043101> du /5a/44/peaklets-ui5hguaz2k-000144
du: cannot access ‘/5a/44/peaklets-ui5hguaz2k-000144’: No such file or directory
Singularity xenonnt-development.simg:/project/lgrandi/rucio/xnt_043101> cd /5a/44/
bash: cd: /5a/44/: No such file or directory
```

This one leads to `DataCorrupted` error. Try this on midway:
```
st.get_array('043101', 'peaklets', keep_columns=('time'))
```
DataCorrupted: Fatal Error while reading file <_io.BufferedReader name='/project/lgrandi/rucio/xnt_043101/5a/44/peaklets-ui5hguaz2k-000144'>: Traceback (most recent call last):
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/io.py", line 54, in _load_file
    data = COMPRESSORS[compressor]['decompress'](data)
zstd.Error: Decompression error: Src size is incorrect

**Comment by FaroutYLq** [comment]
Another example, `xnt_043129`. Pegaus outputs at: `/scratch/yuanlq/workflows/runs/straxen_v2.1.1/xenonnt_offline/43129_0` from OSG login node.
Symptoms below:
- This run failed all event level processing, but `peaklets` and `lone_hits` are stored at Midway, which is indicating that the peak-level processing succeed. 
- Loading the `peaklets` and `lone_hits` from midway has no problem.```python
st.get_array('043129', 'peaklets', keep_columns=('time'))
st.get_array('043129', 'lone_hits', keep_columns=('time'))
```
- Some DIDs are missing from rucio, for example```| xnt_043129:peaklets-ui5hguaz2k-000030        | EFE8B128-283E-450B-B6E7-A712A0E5E799 | ad:2cafee70 | 51.698 MB  |          |
| xnt_043129:peaklets-ui5hguaz2k-000032        | BE800477-8294-405C-AE56-FADB5F41667C | ad:815677f4 | 58.004 MB  |          |``` (from `Singularity xenonnt-development.simg:/project/lgrandi/rucio/xnt_043129> rucio list-files xnt_043129:peaklets-ui5hguaz2k`) Here chunk `000031` is missing from rucio. 
- This explains why we saw the error in `/scratch/yuanlq/workflows/runs/straxen_v2.1.1/xenonnt_offline/43129_0/00/00/combine_ID0000001.out.004`:```
---------------pegasus-multipart
- transfer_attempts:
  - src_url: "file:///srv/pegasus.cZjehh2z6/043129-peaklets-combined.tar.gz"
    src_label: "condorpool"
    dst_url: "gsiftp://xenon-gridftp.grid.uchicago.edu:2811/xenon/workflow_scratch/yuanlq/43129_0/00/00/043129-peaklets-combined.tar.gz"
    dst_label: "staging"
    success: False
    start: 1690480537
    duration: 0.0
    lfn: "043129-peaklets-combined.tar.gz"
  - src_url: "file:///srv/pegasus.cZjehh2z6/043129-peaklets-combined.tar.gz"
    src_label: "condorpool"
    dst_url: "gsiftp://xenon-gridftp.grid.uchicago.edu:2811/xenon/workflow_scratch/yuanlq/43129_0/00/00/043129-peaklets-combined.tar.gz"
    dst_label: "staging"
    success: False
    start: 1690480683
    duration: 0.0
    lfn: "043129-peaklets-combined.tar.gz"
  - src_url: "file:///srv/pegasus.cZjehh2z6/043129-peaklets-combined.tar.gz"
    src_label: "condorpool"
    dst_url: "gsiftp://xenon-gridftp.grid.uchicago.edu:2811/xenon/workflow_scratch/yuanlq/43129_0/00/00/043129-peaklets-combined.tar.gz"
    dst_label: "staging"
    success: False
    start: 1690480985
    duration: 0.0
    lfn: "043129-peaklets-combined.tar.gz"
```
- However, this chunk indeed landed on midway. See below from midway login node:
```
Singularity xenonnt-development.simg:/project/lgrandi/rucio/xnt_043129> find . -type f -name "*peaklets-ui5hguaz2k-000031"
./18/01/peaklets-ui5hguaz2k-000031
```

**Comment by FaroutYLq** [comment]
[This](https://github.com/XENONnT/admix/blob/bddc42c06592e33a81b2431134ec2062c74d2c4b/admix/uploader.py#L51) could explain why we see chunk missing from rucio but actually available on midway.

**Comment by FaroutYLq** [comment]
Since RCC replaced the network courts 2 weeks ago, it was doing well for SR0 reprocessing. (almost 100% success ratio). We will keep this closed for now.
